name: Test on Windows

on:
  push:
    branches:
      - release
  workflow_dispatch:  

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v4  
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --windowed main.py --collect-data resources

      - name: Run EXE
        run: dist/main.exe